language: python

os: linux

install: pip install tox

jobs:
  include:
  - python: "2.7"
    env: TOX_ENV=cov-travis
  - python: "3.6"
    env: TOX_ENV=py36
  - python: "3.6"
    env: TOX_ENV=static
  - python: "3.6"
    env: TOX_ENV=docs

script: tox -e $TOX_ENV

after_success:
- test $TOX_ENV = docs && scripts/push-docs
